// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"time"

	"go-boilerplate/platform/cqrs"
)

// Ensure, that CacheMock does implement cqrs.Cache.
// If this is not the case, regenerate this file with moq.
var _ cqrs.Cache = &CacheMock{}

// CacheMock is a mock implementation of cqrs.Cache.
//
//	func TestSomethingThatUsesCache(t *testing.T) {
//
//		// make and configure a mocked cqrs.Cache
//		mockedCache := &CacheMock{
//			DeleteFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, key string) ([]byte, bool) {
//				panic("mock out the Get method")
//			},
//			GetOrLoadFunc: func(ctx context.Context, key string, ttl time.Duration, load func(ctx context.Context) ([]byte, error)) ([]byte, error) {
//				panic("mock out the GetOrLoad method")
//			},
//			SetFunc: func(ctx context.Context, key string, value []byte, ttl time.Duration)  {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedCache in code that requires cqrs.Cache
//		// and then make assertions.
//
//	}
type CacheMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, key string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) ([]byte, bool)

	// GetOrLoadFunc mocks the GetOrLoad method.
	GetOrLoadFunc func(ctx context.Context, key string, ttl time.Duration, load func(ctx context.Context) ([]byte, error)) ([]byte, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value []byte, ttl time.Duration)

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetOrLoad holds details about calls to the GetOrLoad method.
		GetOrLoad []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// TTL is the ttl argument value.
			TTL time.Duration
			// Load is the load argument value.
			Load func(ctx context.Context) ([]byte, error)
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value []byte
			// TTL is the ttl argument value.
			TTL time.Duration
		}
	}
	lockDelete    sync.RWMutex
	lockGet       sync.RWMutex
	lockGetOrLoad sync.RWMutex
	lockSet       sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *CacheMock) Delete(ctx context.Context, key string) error {
	if mock.DeleteFunc == nil {
		panic("CacheMock.DeleteFunc: method is nil but Cache.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedCache.DeleteCalls())
func (mock *CacheMock) DeleteCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *CacheMock) Get(ctx context.Context, key string) ([]byte, bool) {
	if mock.GetFunc == nil {
		panic("CacheMock.GetFunc: method is nil but Cache.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedCache.GetCalls())
func (mock *CacheMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetOrLoad calls GetOrLoadFunc.
func (mock *CacheMock) GetOrLoad(ctx context.Context, key string, ttl time.Duration, load func(ctx context.Context) ([]byte, error)) ([]byte, error) {
	if mock.GetOrLoadFunc == nil {
		panic("CacheMock.GetOrLoadFunc: method is nil but Cache.GetOrLoad was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Key  string
		TTL  time.Duration
		Load func(ctx context.Context) ([]byte, error)
	}{
		Ctx:  ctx,
		Key:  key,
		TTL:  ttl,
		Load: load,
	}
	mock.lockGetOrLoad.Lock()
	mock.calls.GetOrLoad = append(mock.calls.GetOrLoad, callInfo)
	mock.lockGetOrLoad.Unlock()
	return mock.GetOrLoadFunc(ctx, key, ttl, load)
}

// GetOrLoadCalls gets all the calls that were made to GetOrLoad.
// Check the length with:
//
//	len(mockedCache.GetOrLoadCalls())
func (mock *CacheMock) GetOrLoadCalls() []struct {
	Ctx  context.Context
	Key  string
	TTL  time.Duration
	Load func(ctx context.Context) ([]byte, error)
} {
	var calls []struct {
		Ctx  context.Context
		Key  string
		TTL  time.Duration
		Load func(ctx context.Context) ([]byte, error)
	}
	mock.lockGetOrLoad.RLock()
	calls = mock.calls.GetOrLoad
	mock.lockGetOrLoad.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *CacheMock) Set(ctx context.Context, key string, value []byte, ttl time.Duration) {
	if mock.SetFunc == nil {
		panic("CacheMock.SetFunc: method is nil but Cache.Set was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value []byte
		TTL   time.Duration
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
		TTL:   ttl,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	mock.SetFunc(ctx, key, value, ttl)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedCache.SetCalls())
func (mock *CacheMock) SetCalls() []struct {
	Ctx   context.Context
	Key   string
	Value []byte
	TTL   time.Duration
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value []byte
		TTL   time.Duration
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
