// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"time"

	"go-boilerplate/platform/cqrs"
)

// Ensure, that CacheMock does implement cqrs.Cache.
// If this is not the case, regenerate this file with moq.
var _ cqrs.Cache = &CacheMock{}

// CacheMock is a mock implementation of cqrs.Cache.
//
//	func TestSomethingThatUsesCache(t *testing.T) {
//
//		// make and configure a mocked cqrs.Cache
//		mockedCache := &CacheMock{
//			GetFunc: func(ctx context.Context, key string) ([]byte, bool) {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(ctx context.Context, key string, value []byte, ttl time.Duration)  {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedCache in code that requires cqrs.Cache
//		// and then make assertions.
//
//	}
type CacheMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) ([]byte, bool)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value []byte, ttl time.Duration)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value []byte
			// TTL is the ttl argument value.
			TTL time.Duration
		}
	}
	lockGet sync.RWMutex
	lockSet sync.RWMutex
}

// Get calls GetFunc.
func (mock *CacheMock) Get(ctx context.Context, key string) ([]byte, bool) {
	if mock.GetFunc == nil {
		panic("CacheMock.GetFunc: method is nil but Cache.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedCache.GetCalls())
func (mock *CacheMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *CacheMock) Set(ctx context.Context, key string, value []byte, ttl time.Duration) {
	if mock.SetFunc == nil {
		panic("CacheMock.SetFunc: method is nil but Cache.Set was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value []byte
		TTL   time.Duration
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
		TTL:   ttl,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	mock.SetFunc(ctx, key, value, ttl)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedCache.SetCalls())
func (mock *CacheMock) SetCalls() []struct {
	Ctx   context.Context
	Key   string
	Value []byte
	TTL   time.Duration
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value []byte
		TTL   time.Duration
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
