// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"io"
	"sync"
	"time"

	"go-boilerplate/platform/storage/blob"
)

// Ensure, that ObjectStoreMock does implement blob.ObjectStore.
// If this is not the case, regenerate this file with moq.
var _ blob.ObjectStore = &ObjectStoreMock{}

// ObjectStoreMock is a mock implementation of blob.ObjectStore.
//
//	func TestSomethingThatUsesObjectStore(t *testing.T) {
//
//		// make and configure a mocked blob.ObjectStore
//		mockedObjectStore := &ObjectStoreMock{
//			DeleteFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Delete method")
//			},
//			ExistsFunc: func(ctx context.Context, key string) (bool, error) {
//				panic("mock out the Exists method")
//			},
//			GetFunc: func(ctx context.Context, key string) (io.ReadCloser, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, prefix string) ([]string, error) {
//				panic("mock out the List method")
//			},
//			PresignGetFunc: func(ctx context.Context, key string, ttl time.Duration, opts ...blob.PresignOption) (string, error) {
//				panic("mock out the PresignGet method")
//			},
//			PutFunc: func(ctx context.Context, key string, r io.Reader, size int64, contentType string) error {
//				panic("mock out the Put method")
//			},
//		}
//
//		// use mockedObjectStore in code that requires blob.ObjectStore
//		// and then make assertions.
//
//	}
type ObjectStoreMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, key string) error

	// ExistsFunc mocks the Exists method.
	ExistsFunc func(ctx context.Context, key string) (bool, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) (io.ReadCloser, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, prefix string) ([]string, error)

	// PresignGetFunc mocks the PresignGet method.
	PresignGetFunc func(ctx context.Context, key string, ttl time.Duration, opts ...blob.PresignOption) (string, error)

	// PutFunc mocks the Put method.
	PutFunc func(ctx context.Context, key string, r io.Reader, size int64, contentType string) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Exists holds details about calls to the Exists method.
		Exists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Prefix is the prefix argument value.
			Prefix string
		}
		// PresignGet holds details about calls to the PresignGet method.
		PresignGet []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// TTL is the ttl argument value.
			TTL time.Duration
			// Opts is the opts argument value.
			Opts []blob.PresignOption
		}
		// Put holds details about calls to the Put method.
		Put []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// R is the r argument value.
			R io.Reader
			// Size is the size argument value.
			Size int64
			// ContentType is the contentType argument value.
			ContentType string
		}
	}
	lockDelete     sync.RWMutex
	lockExists     sync.RWMutex
	lockGet        sync.RWMutex
	lockList       sync.RWMutex
	lockPresignGet sync.RWMutex
	lockPut        sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *ObjectStoreMock) Delete(ctx context.Context, key string) error {
	if mock.DeleteFunc == nil {
		panic("ObjectStoreMock.DeleteFunc: method is nil but ObjectStore.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedObjectStore.DeleteCalls())
func (mock *ObjectStoreMock) DeleteCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Exists calls ExistsFunc.
func (mock *ObjectStoreMock) Exists(ctx context.Context, key string) (bool, error) {
	if mock.ExistsFunc == nil {
		panic("ObjectStoreMock.ExistsFunc: method is nil but ObjectStore.Exists was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockExists.Lock()
	mock.calls.Exists = append(mock.calls.Exists, callInfo)
	mock.lockExists.Unlock()
	return mock.ExistsFunc(ctx, key)
}

// ExistsCalls gets all the calls that were made to Exists.
// Check the length with:
//
//	len(mockedObjectStore.ExistsCalls())
func (mock *ObjectStoreMock) ExistsCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockExists.RLock()
	calls = mock.calls.Exists
	mock.lockExists.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ObjectStoreMock) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	if mock.GetFunc == nil {
		panic("ObjectStoreMock.GetFunc: method is nil but ObjectStore.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedObjectStore.GetCalls())
func (mock *ObjectStoreMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ObjectStoreMock) List(ctx context.Context, prefix string) ([]string, error) {
	if mock.ListFunc == nil {
		panic("ObjectStoreMock.ListFunc: method is nil but ObjectStore.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Prefix string
	}{
		Ctx:    ctx,
		Prefix: prefix,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, prefix)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedObjectStore.ListCalls())
func (mock *ObjectStoreMock) ListCalls() []struct {
	Ctx    context.Context
	Prefix string
} {
	var calls []struct {
		Ctx    context.Context
		Prefix string
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// PresignGet calls PresignGetFunc.
func (mock *ObjectStoreMock) PresignGet(ctx context.Context, key string, ttl time.Duration, opts ...blob.PresignOption) (string, error) {
	if mock.PresignGetFunc == nil {
		panic("ObjectStoreMock.PresignGetFunc: method is nil but ObjectStore.PresignGet was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Key  string
		TTL  time.Duration
		Opts []blob.PresignOption
	}{
		Ctx:  ctx,
		Key:  key,
		TTL:  ttl,
		Opts: opts,
	}
	mock.lockPresignGet.Lock()
	mock.calls.PresignGet = append(mock.calls.PresignGet, callInfo)
	mock.lockPresignGet.Unlock()
	return mock.PresignGetFunc(ctx, key, ttl, opts...)
}

// PresignGetCalls gets all the calls that were made to PresignGet.
// Check the length with:
//
//	len(mockedObjectStore.PresignGetCalls())
func (mock *ObjectStoreMock) PresignGetCalls() []struct {
	Ctx  context.Context
	Key  string
	TTL  time.Duration
	Opts []blob.PresignOption
} {
	var calls []struct {
		Ctx  context.Context
		Key  string
		TTL  time.Duration
		Opts []blob.PresignOption
	}
	mock.lockPresignGet.RLock()
	calls = mock.calls.PresignGet
	mock.lockPresignGet.RUnlock()
	return calls
}

// Put calls PutFunc.
func (mock *ObjectStoreMock) Put(ctx context.Context, key string, r io.Reader, size int64, contentType string) error {
	if mock.PutFunc == nil {
		panic("ObjectStoreMock.PutFunc: method is nil but ObjectStore.Put was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Key         string
		R           io.Reader
		Size        int64
		ContentType string
	}{
		Ctx:         ctx,
		Key:         key,
		R:           r,
		Size:        size,
		ContentType: contentType,
	}
	mock.lockPut.Lock()
	mock.calls.Put = append(mock.calls.Put, callInfo)
	mock.lockPut.Unlock()
	return mock.PutFunc(ctx, key, r, size, contentType)
}

// PutCalls gets all the calls that were made to Put.
// Check the length with:
//
//	len(mockedObjectStore.PutCalls())
func (mock *ObjectStoreMock) PutCalls() []struct {
	Ctx         context.Context
	Key         string
	R           io.Reader
	Size        int64
	ContentType string
} {
	var calls []struct {
		Ctx         context.Context
		Key         string
		R           io.Reader
		Size        int64
		ContentType string
	}
	mock.lockPut.RLock()
	calls = mock.calls.Put
	mock.lockPut.RUnlock()
	return calls
}
