// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"go-boilerplate/platform/security/audit"
)

// Ensure, that StoreMock does implement audit.Store.
// If this is not the case, regenerate this file with moq.
var _ audit.Store = &StoreMock{}

// StoreMock is a mock implementation of audit.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked audit.Store
//		mockedStore := &StoreMock{
//			RecordFunc: func(ctx context.Context, e audit.Entry) error {
//				panic("mock out the Record method")
//			},
//		}
//
//		// use mockedStore in code that requires audit.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// RecordFunc mocks the Record method.
	RecordFunc func(ctx context.Context, e audit.Entry) error

	// calls tracks calls to the methods.
	calls struct {
		// Record holds details about calls to the Record method.
		Record []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// E is the e argument value.
			E audit.Entry
		}
	}
	lockRecord sync.RWMutex
}

// Record calls RecordFunc.
func (mock *StoreMock) Record(ctx context.Context, e audit.Entry) error {
	if mock.RecordFunc == nil {
		panic("StoreMock.RecordFunc: method is nil but Store.Record was just called")
	}
	callInfo := struct {
		Ctx context.Context
		E   audit.Entry
	}{
		Ctx: ctx,
		E:   e,
	}
	mock.lockRecord.Lock()
	mock.calls.Record = append(mock.calls.Record, callInfo)
	mock.lockRecord.Unlock()
	return mock.RecordFunc(ctx, e)
}

// RecordCalls gets all the calls that were made to Record.
// Check the length with:
//
//	len(mockedStore.RecordCalls())
func (mock *StoreMock) RecordCalls() []struct {
	Ctx context.Context
	E   audit.Entry
} {
	var calls []struct {
		Ctx context.Context
		E   audit.Entry
	}
	mock.lockRecord.RLock()
	calls = mock.calls.Record
	mock.lockRecord.RUnlock()
	return calls
}
