// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"go-boilerplate/platform/security/auth"
)

// Ensure, that VerifierMock does implement auth.Verifier.
// If this is not the case, regenerate this file with moq.
var _ auth.Verifier = &VerifierMock{}

// VerifierMock is a mock implementation of auth.Verifier.
//
//	func TestSomethingThatUsesVerifier(t *testing.T) {
//
//		// make and configure a mocked auth.Verifier
//		mockedVerifier := &VerifierMock{
//			VerifyFunc: func(ctx context.Context, rawToken string) (auth.Principal, error) {
//				panic("mock out the Verify method")
//			},
//		}
//
//		// use mockedVerifier in code that requires auth.Verifier
//		// and then make assertions.
//
//	}
type VerifierMock struct {
	// VerifyFunc mocks the Verify method.
	VerifyFunc func(ctx context.Context, rawToken string) (auth.Principal, error)

	// calls tracks calls to the methods.
	calls struct {
		// Verify holds details about calls to the Verify method.
		Verify []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RawToken is the rawToken argument value.
			RawToken string
		}
	}
	lockVerify sync.RWMutex
}

// Verify calls VerifyFunc.
func (mock *VerifierMock) Verify(ctx context.Context, rawToken string) (auth.Principal, error) {
	if mock.VerifyFunc == nil {
		panic("VerifierMock.VerifyFunc: method is nil but Verifier.Verify was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		RawToken string
	}{
		Ctx:      ctx,
		RawToken: rawToken,
	}
	mock.lockVerify.Lock()
	mock.calls.Verify = append(mock.calls.Verify, callInfo)
	mock.lockVerify.Unlock()
	return mock.VerifyFunc(ctx, rawToken)
}

// VerifyCalls gets all the calls that were made to Verify.
// Check the length with:
//
//	len(mockedVerifier.VerifyCalls())
func (mock *VerifierMock) VerifyCalls() []struct {
	Ctx      context.Context
	RawToken string
} {
	var calls []struct {
		Ctx      context.Context
		RawToken string
	}
	mock.lockVerify.RLock()
	calls = mock.calls.Verify
	mock.lockVerify.RUnlock()
	return calls
}
