-- Collapsed baseline — the boilerplate was never deployed, so the original
-- incremental chain was merged into one authoritative migration. DO NOT
-- re-collapse a live schema: a deployed database has already applied the prior
-- chain.
--
-- This baseline merges the original 7-file chain:
--   00001 orders_read + inbox
--   00002 orders_read.created_at + keyset index
--   00003 audit_log + action/actor indexes
--   00004 audit_log append-only ownership transfer (preserved verbatim, last)
--   00005 audit_log hash-chain columns + audit_chain_head genesis
--   00006 audit_log chain_id + chain index, audit_chain_head singleton dropped
--   00007 product_views
-- The hash-chain columns (00005) and chain_id (00006) are folded into the
-- audit_log create table — the table is app-owned until the ownership-transfer
-- do-block (00004) runs LAST on the final-shape table. audit_chain_head is
-- created with the genesis seed and WITHOUT the singleton check (the chain ends
-- up sharded; the old chain added then dropped the singleton). The schema-diff
-- oracle (scripts/migoracle) proves this is byte-identical to the old chain.

-- +goose Up
create table orders_read (
    order_id     uuid        primary key,
    customer_id  text        not null,
    amount_cents bigint      not null,
    currency     text        not null,
    status       text        not null,
    updated_at   timestamptz not null default now(),
    -- created_at backs the keyset pagination cursor of GET /v1/orders
    -- (ordered by (created_at, order_id) descending).
    created_at   timestamptz not null default now()
);
create index orders_read_created_at_idx on orders_read (created_at desc, order_id desc);

create table inbox (
    consumer     text        not null,
    message_id   text        not null,
    processed_at timestamptz not null default now(),
    primary key (consumer, message_id)
);

-- Audit trail (platform/security/audit schema): the gateway serves the
-- admin-only DSAR read endpoint GET /v1/audit over this table. Same DDL as
-- the other services' audit_log so audit.PgStore works unchanged; the
-- (actor, created_at) index backs the by-actor read path (QueryByActor).
--
-- The hash-chain columns (prev_hash, entry_hash) and chain_id are folded in
-- here: audit.Record / audit.VerifyChain use them for tamper-evidence, and
-- chain_id default 1 (sharded chains, ADR-0018) keeps every write on the
-- single global chain (head id=1) until AUDIT_CHAIN_SHARDS > 1.
create table audit_log (
    id          bigint generated by default as identity primary key,
    actor       text        not null,
    action      text        not null,
    subject     text        not null,
    metadata    jsonb       not null default '{}'::jsonb,
    created_at  timestamptz not null default now(),
    prev_hash   bytea,
    entry_hash  bytea,
    chain_id    smallint    not null default 1
);
create index audit_log_action_idx on audit_log (action, created_at);
create index audit_log_actor_idx on audit_log (actor, created_at);
create index audit_log_chain_idx on audit_log (chain_id, id);

create table audit_chain_head (
    id         smallint primary key default 1,
    last_hash  bytea       not null,
    updated_at timestamptz not null default now()
);

insert into audit_chain_head (id, last_hash)
values (1, '\x0000000000000000000000000000000000000000000000000000000000000000'::bytea);

-- app reads + advances (and lazily inserts sharded — ADR-0018) chain-head rows;
-- grant to the DATABASE OWNER (runtime app role) so it works under a privileged/
-- superuser migrate role (PG_MIGRATE_URL) too, not just migrate-as-app.
-- +goose StatementBegin
do $$
declare
    app_role text := (select pg_catalog.pg_get_userbyid(datdba)
                      from pg_database where datname = current_database());
begin
    execute format('grant select, insert, update on audit_chain_head to %I', app_role);
end
$$;
-- +goose StatementEnd

-- High-volume, low-value demo write (A2): one INSERT, NO outbox — so the
-- RecordProductView command can run with ConsistencyPolicy Eventual +
-- Transactional:false (no wrapping tx, async best-effort audit). Contrast with
-- the order flow, which is Strong/effectively-once via the Kafka outbox.
create table product_views (
    id          bigserial   primary key,
    product_id  text        not null,
    viewer      text        not null,
    viewed_at   timestamptz not null default now()
);

-- Append-only audit_log for the gateway (mirrors the platform audit migration
-- 00003_audit_append_only): the app role may INSERT + SELECT but never
-- UPDATE/DELETE. See deploy/postgres/init.sql for the role split and the
-- privileged retention path (PG_AUDIT_ADMIN_URL / audit_admin).
--
-- The gateway's audit_log is identity-based (bigint generated by default as
-- identity), so there is no separate sequence to grant — the identity sequence
-- is owned by the column and INSERT alone covers it.
--
-- OWNERSHIP IS LOAD-BEARING: an OWNER keeps UPDATE/DELETE implicitly, so unless
-- the table is owned by a NON-app role the REVOKE is a no-op. When audit_admin
-- exists (deploy/postgres/init.sql), transfer ownership to it and re-grant the
-- app role only INSERT + SELECT so the REVOKE actually denies the app's
-- UPDATE/DELETE. Skipped (best-effort) where audit_admin is absent — see the
-- platform audit migration 00003 for the full rationale and trade-off.
--
-- This do-block runs LAST, after audit_log already has its final shape
-- (hash-chain columns + chain_id), so the per-ALTER SET-ROLE dance of the old
-- chain is unnecessary — the transfer is the only owner-sensitive step.
-- +goose StatementBegin
-- Grant/revoke against the DATABASE OWNER (the runtime app role), not
-- current_user, so this works whether migrations run as app or a privileged/
-- superuser migrate role (PG_MIGRATE_URL). See platform audit 00003.
do $$
declare
    app_role text := (select pg_catalog.pg_get_userbyid(datdba)
                      from pg_database where datname = current_database());
begin
    if exists (select 1 from pg_roles where rolname = 'audit_admin') then
        execute 'alter table audit_log owner to audit_admin';
        -- Act AS the new owner — app is a non-owner after the transfer.
        set local role audit_admin;
        execute format('grant select, insert on audit_log to %I', app_role);
        execute format('revoke update, delete on audit_log from %I', app_role);
        reset role;
    else
        execute format('revoke update, delete on audit_log from %I', app_role);
    end if;
end
$$;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
do $$
begin
    if exists (select 1 from pg_roles where rolname = 'audit_admin') then
        execute 'alter table audit_log owner to ' || quote_ident(current_user);
    end if;
    execute format('grant update, delete on audit_log to %I', current_user);
end
$$;
-- +goose StatementEnd
drop table product_views;
drop table audit_chain_head;
drop table audit_log;
drop table inbox;
drop table orders_read;
