-- +goose Up
-- Append-only audit_log for the gateway (mirrors the platform audit migration
-- 00003_audit_append_only): the app role may INSERT + SELECT but never
-- UPDATE/DELETE. See deploy/postgres/init.sql for the role split and the
-- privileged retention path (PG_AUDIT_ADMIN_URL / audit_admin).
--
-- The gateway's audit_log (00003) is identity-based (bigint generated by
-- default as identity), so there is no separate sequence to grant — the
-- identity sequence is owned by the column and INSERT alone covers it.
--
-- +goose StatementBegin
do $$
begin
    execute format('revoke update, delete on audit_log from %I', current_user);
    if exists (select 1 from pg_roles where rolname = 'audit_admin') then
        execute 'grant select, delete on audit_log to audit_admin';
    end if;
end
$$;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
do $$
begin
    execute format('grant update, delete on audit_log to %I', current_user);
end
$$;
-- +goose StatementEnd
