-- +goose Up
-- Audit trail (platform/security/audit schema): the gateway serves the
-- admin-only DSAR read endpoint GET /v1/audit over this table. Same DDL as
-- the other services' audit_log so audit.PgStore works unchanged; the
-- (actor, created_at) index backs the by-actor read path (QueryByActor).
create table audit_log (
    id          bigint generated by default as identity primary key,
    actor       text        not null,
    action      text        not null,
    subject     text        not null,
    metadata    jsonb       not null default '{}'::jsonb,
    created_at  timestamptz not null default now()
);
create index audit_log_action_idx on audit_log (action, created_at);
create index audit_log_actor_idx on audit_log (actor, created_at);

-- +goose Down
drop table audit_log;
